import type { Metadata } from "next";
import {
  Fjalla_One,
  Geist,
  Geist_Mono,
  Source_Code_Pro,
} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const fjalla = Fjalla_One({
  variable: "--fjalla",
  subsets: ["latin"],
  weight: "400",
});

const sourcesans = Source_Code_Pro({
  variable: "--sourcesans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${fjalla?.variable} ${sourcesans?.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
